### ISSUE TITLE
Create docs for BBGGEZ on Crates.io

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/bbggez#1]
Currently the [crates.io](https://crates.io/crates/bbggez) page doesn't have a link to the documentation. We should figure out how to generate the docs website and add a link.

**Comment by BrooksPatton** [comment]
I found that the docs are auto generated and hosted at [https://docs.rs/bbggez/0.0.0/bbggez/](https://docs.rs/bbggez/0.0.0/bbggez/)

**Comment by redoxeon** [comment]
So are you just wanting a link in the readme for that docs.rs page? If so I could add a section and make a pull request real fast

**Comment by BrooksPatton** [comment]
I want to figure out how to get a official link to the documentation page in crates.io

**Comment by BrooksPatton** [comment]
I'm thinking there is something that might be able to be done in the cargo.toml file

**Comment by baileyn** [comment]
It looks like there's a link already on the crates.io page.

I found the [manifest documentation](https://doc.rust-lang.org/cargo/reference/manifest.html#the-documentation-field-optional). It seems like if nothing is specified in the `documentation` field, then it will automatically link to the docs.rs documentation page.

**Comment by BrooksPatton** [comment]
Strange, I could swear that link wasn't there earlier.

I guess that closes this issue, thanks @baileyn!
