### ISSUE TITLE
Do we want to wrap around ggez

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/bbggez#10]
I'm not sure we do for this library, maybe another project?

Also what would that look like in code. Let's create a discussion here.

**Comment by AndCotOli** [comment]
I think it would be really nice to have a _simpler_ way to do things in ggez, and things like physics and window borders built in as well.

In my opinion, wrapping around ggez gives us the option to do more things _under the hood_.

**Comment by dannyfritz** [comment]
I say no to wrapping ggez. I think this library should extend ggez instead of wrap it.

**Comment by BrooksPatton** [comment]
To make sure I understand:

Creating and returning GGEZ meshes is good because it is extending GGEZ. If we were to return our own object then we would be wrapping.

I agree, lets stick with extending. We should still be able to do some really interesting things under the hood @AndCotOli .

**Comment by AndCotOli** [comment]
Maybe _wrap_ wasn't the correct word.

What I ment was to give the user a _simpler_ way to access ggez, while returning ggez objects.

**Comment by BrooksPatton** [comment]
Yes, I think that is it! I'm going to close this issue as I think we now know we are extending GGEZ and making life simpler for ourselves so we can build more complicated things faster!
