### ISSUE TITLE
Create a Mesh Struct

### ISSUE THREAD

**Issue by AndCotOli** [brooks-builds/bbggez#15]
Functions that create meshes are starting to get messy.

We could create a mesh structure to store them in the same place.

**Comment by BrooksPatton** [comment]
If we implemented the file restructuring in #17 would that solve this issue?

**Comment by AndCotOli** [comment]
I think so @BrooksPatton , since the mesh mod keeps all of them in the same place/file.

**Comment by BrooksPatton** [comment]
Ok, then lets move this conversation over to #17 for meshes
