### ISSUE TITLE
New File Structure

### ISSUE THREAD

**Issue by AndCotOli** [brooks-builds/bbggez#17]
To avoid merge conflicts, and make the code more organized, I've made up this file structure.

### src folder
```
multiple_part_module/
  - module_part_1.rs
  - module_part_2.rs
tests/
  - module_1_test.rs
  - module_2_test.rs
  - ...
module_1.rs
module_2.rs
module_3.rs
main.rs
```

### main.rs
```rust
extern crate random //Crates that won't get exported

pub extern crate ggez //Expose ggez so users can do custom things

pub mod module_1
pub mod module_2
pub mod module_3
mod private_module
```

**Comment by AndCotOli** [comment]
Example Available at: https://github.com/AndCotOli/bbggez/tree/new-file-structure

**Comment by BrooksPatton** [comment]
There are some parts that I like a lot, like the different files broken apart (lib -> mesh -> circle) and so on.

I'm not sure how I feel about the tests as a separate mod. I'll think about that. 

Does anyone else have any thoughts on this?

**Comment by BrooksPatton** [comment]
I like the idea of having the unit tests in the same file as the code, it's one of my favorite features of Rust. What do we feel about removing the tests directory and breaking the files into smaller 'unit' files and having the tests inside them?
