### ISSUE TITLE
Create a script to run all the examples in a row

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/bbggez#21]
This will make it easier to test the code base visually before merging in and updating the library on crates.io.

**Comment by VioletasTheThird** [comment]
I'll do this

**Comment by VioletasTheThird** [comment]
actually, before I created that PR i should have asked, should the script be a simple shell script or something like a python script?

**Comment by BrooksPatton** [comment]
In my mind, I was thinking of a shell script, but I wouldn't mind a python script as long as my computer can run it without installing anything special. I have python3 installed so that could work.

I'm also okay if the script runs one at a time and I just glance at it for errors and hit `f4` to close it and move onto the next one.

Should I assign this to you @VioletasTheThird?

**Comment by BrooksPatton** [comment]
Nevermind, you beat me to it and already got a PR in!
