### ISSUE TITLE
Random location in arena

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/bbggez#22]
It would be nice to have a function that takes in the arena size and returns a random location inside the arena.

**Comment by baileyn** [comment]
I'd like to tackle this. Would this function go in the `Utility` implementation?  Additionally, would the following signature be appropriate?

```rust
pub fn random_location(width: f32, height: f32) -> (f32, f32)
```

**Comment by baileyn** [comment]
I would like to work on this. Would this be an appropriate signature for the function?

```rust
pub fn random_location(&mut self, width: f32, height: f32) -> (f32, f32)
```

**Comment by BrooksPatton** [comment]
I think that would work. The way I'm working with this API is that if we want changes we'll have more issues in the future. For now, that looks like a great start.

Thanks for taking this on @baileyn!
