### ISSUE TITLE
Tests fail sometimes.

### ISSUE THREAD

**Issue by baileyn** [brooks-builds/bbggez#27]
I just ran the tests and received a failure. There's not a genuine issue because running the tests again were successful, but I think this should still be addressed.

```
Nicholass-MacBook-Pro:bbggez nbailey$ cargo test
   Compiling bbggez v0.5.0 (/Users/nbailey/git/bbggez)
    Finished dev [unoptimized + debuginfo] target(s) in 4.89s
     Running target/debug/deps/bbggez-02d635cba9813948

running 3 tests
test tests::generates_random_location ... ok
test tests::creates_a_random_color ... ok
test tests::creates_a_random_dark_color ... FAILED

failures:

---- tests::creates_a_random_dark_color stdout ----
thread 'tests::creates_a_random_dark_color' panicked at 'assertion failed: color.r + color.g + color.b !=
    another_color.r + another_color.g + another_color.b', src/lib.rs:163:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


failures:
    tests::creates_a_random_dark_color

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

Currently the tests `creates_a_random_color`, `creates_a_random_dark_color`, and `generates_random_location` can potentially fail at random due to the random nature of functions being defined.

Currently, `creates_a_random_color` and `creates_a_random_dark_color` have tests that create one random color after another and vaguely assert that they're not equal. Due to the random nature of the functions it's possible, but not probable, that they'll be the same. 

`assert!(color.r + color.g + color.b != another_color.r + another_color.g + another_color.b);`

Making this strictly check if the`r`, `g`, and `b` values are the same would definitely increase the entropy, but I think it could still fail because there are no guarantees that the exact same color won't be generated twice in a row.

The `generates_random_location` follows suit by testing two generated locations

`assert_ne!(first, second);`

**Comment by BrooksPatton** [comment]
The tests are a bit better now that @dannyfritz has made some changes to the code. I understand that they may still fail, and when it does maybe we should move to just checking that function runs properly and then test in the examples.

I'll close this ticket to track this decision as decided for now.

Thanks @baileyn !
