### ISSUE TITLE
Add example for create random location

### ISSUE THREAD

**Issue by BrooksPatton** [brooks-builds/bbggez#28]
We don't have an example for creating a random location. Let's create a example file to show off how that function works.

**Comment by BrooksPatton** [comment]
To clarify, I'm thinking an example file in the example folder.

**Comment by plwai** [comment]
Hi, I would like to grab this issue.

**Comment by BrooksPatton** [comment]
You've got it! 

I don't know why I didn't get any more information on that crash in the example.
